# Generated by Django 3.0.6 on 2021-10-04 18:37

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('published_date', models.CharField(max_length=20, null=True)),
                ('average_rating', models.PositiveIntegerField(null=True)),
                ('ratings_counts', models.PositiveIntegerField(null=True)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(upload_to='../static/images/')),
                ('authors', models.ManyToManyField(to='book_db.Author')),
                ('categories', models.ManyToManyField(to='book_db.Category')),
            ],
        ),
    ]
