# Generated by Django 3.0.6 on 2021-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('authors', models.CharField(max_length=100, null=True)),
                ('published_date', models.CharField(max_length=20, null=True)),
                ('categories', models.CharField(max_length=280, null=True)),
                ('average_rating', models.PositiveIntegerField(null=True)),
                ('ratings_counts', models.PositiveIntegerField(null=True)),
                ('thumbnail', models.URLField(null=True)),
            ],
        ),
    ]
