# Generated by Django 3.0.6 on 2021-10-04 21:05

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0002_auto_20211004_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(default=None, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media'),
        ),
    ]
