# Generated by Django 3.0.6 on 2021-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0003_auto_20211004_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
