# Generated by Django 3.0.6 on 2021-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0005_auto_20211004_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
